// <auto-generated />
namespace TrabalhoDM106.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class AddProdutoEAddRules : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddProdutoEAddRules));
        
        string IMigrationMetadata.Id
        {
            get { return "202106231312166_AddProdutoEAddRules"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
